### ISSUE TITLE
Add Scoring

### ISSUE THREAD

**Issue by AndreasGocht** [score-p/scorep_cli_score#2]
We missed to implement the scoring, i.e. the estimated size of the trace. Please check which scorep-score functions we can reuse for this task.

Please also check if it is possible to implement a scoring for each function.

**Comment by machtert** [comment]
For the computation of the estimated size you need access to private member functions and variables, for example for `m_total_buf` you need `bytes_per_hit` from SCOREP_Score_Estimator::getEventSize() which is a private member function. That function uses `m_events` which is also a private member variable.
